# global:
#   scrape_interval: 1s
#   evaluation_interval: 1s

# scrape_configs:
#   - job_name: 'ray'
#     file_sd_configs:
#       - files:
#         - '/app/SharedVolume/prom_metrics_service_discovery.json'
# global config
global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 10s 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          group: 'cadvisor'