
global:
  scrape_interval:     1s
  evaluation_interval: 1s

rule_files:
scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 1s 
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          group: 'cadvisor'